Controllers/SecureController.cs
using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using AuthenticationExample.Models;
using AuthenticationExample.Services.Interfaces;
using Microsoft.AspNetCore.Http;
using AuthenticationExample.Helpers;
using AuthenticationExample.Controllers.Base;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace AuthenticationExample.Controllers
{
    [ClaimRequirement(SecureClaimTypes.Permission, "Admin,Read")]
    public class SecureController : BaseController
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly IUserProfileService _userProfileService;
        private readonly IIAMService _iamService;

        public SecureController(IAuthenticationService authenticationService,
            IUserProfileService userProfileService,
            IIAMService iamService)
        {
            _authenticationService = authenticationService;
            _userProfileService = userProfileService;
            _iamService = iamService;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [ClaimRequirement(SecureClaimTypes.Permission, "Admin")]
        public IActionResult Admin()
        {
            return View();
        }

        public IActionResult NoAccess()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View(new UserProfileUpdateResult());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Profile([FromForm] ProfileFields profileFields)
        {
            var result = new UserProfileUpdateResult
            {
                Reason = UserProfileUpdateResultReason.Error
            };
            var user = (User)HttpContext.Items["User"];
            if (user != null)
            {
                if (user.MigratedUserId != null)
                {
                    result = _iamService.UpdateUserProfile(profileFields);
                    user = _iamService.GetCachedUser();
                    HttpContext.Items["User"] = user;
                }
                else
                {
                    profileFields.UserId = user.UserId;
                    result = _userProfileService.UpdateUserProfile(profileFields);
                }                
            }

            return View(result);
        }
    }
}

Views/Secure/Admin.cshtml
@{
    ViewData["Title"] = "Secure Page - Admin";
}

<div class="jumbotron">
    <div class="container">
        <h1>Adminstration Page</h1>
        <p>This page contains administrative functions for the site.</p>
        <p><a class="btn btn-info btn-lg" asp-area="" asp-controller="Secure" asp-action="Index">&laquo; Go Back</a></p>
    </div>
</div>

Views/Secure/Index.cshtml
@using AuthenticationExample.Models;
@{
    ViewBag.User = Context.Items["User"];
    ViewData["Title"] = "Secure Page";
}

<div class="jumbotron">
    <div class="container">
        <h1>Welcome @ViewBag.User.FirstName @ViewBag.User.LastName!</h1>
        @if (ViewBag.User != null
            && ViewBag.User.IsAdmin)
        {
            <p>Signed in as an administrator.</p>
            <p><a class="btn btn-primary btn-lg" asp-area="" asp-controller="Secure" asp-action="Admin">View Admin Page &raquo;</a></p>
        }
        else
        {
            <p>Signed in as a regular user.</p>
        }
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Authentication</h2>
            <p>The example uses a simple session cookie and SQL Server database backend to store user and session data.</p>
        </div>
        <div class="col-md-4">
            <h2>Profile</h2>
            <p>The user profile is editable, along with the username and password.</p>
            <p><a class="btn btn-secondary" asp-area="" asp-controller="Secure" asp-action="Profile">Edit User Profile &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Security</h2>
            <p>The sign-in session automatically expires after 10 minutes of inactivity for extra security.  A prompt appears after 9 minutes to allow extension of the session.</p>            
        </div>
    </div>
</div>

Views/Secure/NoAccess.cshtml
@{
    ViewData["Title"] = "Secure Page - No Access";
}

<div class="jumbotron">
    <div class="container">
        <h1>Secure Page</h1>
        <p>Please contact an administrator to access this page.</p>
        <p><a class="btn btn-info btn-lg" asp-area="" asp-controller="Secure" asp-action="Index">&laquo; Go Back</a></p>
    </div>
</div>

Views/Secure/Profile.cshtml
@using AuthenticationExample.Models
@using AuthenticationExample.Helpers
@model UserProfileUpdateResult
@{
    ViewBag.User = Context.Items["User"];
    ViewData["Title"] = "Secure Page - Profile";
}

@if (ViewBag.User != null)
{    
    var isAdmin = ViewBag.User.ClaimsList.Contains("Admin");
    var isRead = ViewBag.User.ClaimsList.Contains("Read");

    var isError = Model.Reason == UserProfileUpdateResultReason.Error;
    var isInvalidCurrentPassword = Model.Reason == UserProfileUpdateResultReason.InvalidCurrentPassword;
    var isPasswordsDoNotMatch = Model.Reason == UserProfileUpdateResultReason.PasswordsDoNotMatch;
    var isPasswordUpdateError = Model.Reason == UserProfileUpdateResultReason.PasswordUpdateError;
    var isUsernameMustBeUnique = Model.Reason == UserProfileUpdateResultReason.UsernameMustBeUnique;
    var isSMSUpdateError = Model.Reason == UserProfileUpdateResultReason.SMSUpdateError;
    var isPermissionUpdateError = Model.Reason == UserProfileUpdateResultReason.PermissionUpdateError;
    var isSuccess = Model.Reason == UserProfileUpdateResultReason.Success;

    <style>
        .form-control.is-valid:focus, custom-select.form-control.is-valid:focus, .was-validated :valid.form-control { 
            border-color:inherit !important;
            background-image: inherit !important;
            box-shadow:inherit !important;
        }
    </style>
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Edit Profile</h5>
            @if (isSuccess)
            {
                <div class="alert alert-success">
                    The profile was successfully updated!
                </div>
            }
            else if (isError)
            {
                <div class="alert alert-danger">
                    The profile could not be updated.  Please try again.
                    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
                    {
                        <br /><br />
                        <span>@Model.ErrorMessage</span>
                    }
                </div>
            }

            @if (isPermissionUpdateError)
            {
                <div class="alert alert-danger">
                    The permissions could not be updated.  Please try again.
                </div>
            }

            @if (isPasswordUpdateError)
            {
                <div class="alert alert-danger">
                    The password could not be updated:
                    <br /><br />
                    @Model.ErrorMessage
                </div>
            }

            <form method="post" action="@Url.Content("~/Secure/Profile")" class="needs-validation" novalidate>
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label for="CurrentPassword">Current Password (Required to make updates)</label>
                    <input type="password" class="form-control @{ if (isInvalidCurrentPassword) { WriteLiteral("is-invalid"); } }" id="CurrentPassword" name="CurrentPassword" value="" required>
                    <div class="invalid-feedback">                        
                        @if (isInvalidCurrentPassword) 
                        { 
                            <span>The password entered is invalid.  Please try again.</span>
                        }
                        else 
                        {
                            <span>Please enter the current password.</span>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <label for="Username">Username</label>
                    <input type="text" class="form-control @{ if (isUsernameMustBeUnique) { WriteLiteral("is-invalid"); } }" id="Username" name="Username" value="@ViewBag.User.Username" required>
                    <div class="invalid-feedback">
                        @if (isUsernameMustBeUnique) 
                        { 
                            <span>The username must be unique.  Please try again.</span>
                        }
                        else 
                        {
                            <span>Please enter a username.</span>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#updatePassword">
                        Update Password
                    </button>
                </div>
                <div class="collapse" id="updatePassword">
                    <div class="card card-body bg-light">
                        <div class="form-group">
                            <label for="Password">New Password</label>
                            <input type="password" class="form-control @{ if (isPasswordsDoNotMatch || isPasswordUpdateError) { WriteLiteral("is-invalid"); } }" id="Password" name="Password" value="">
                        </div>
                        <div class="form-group">
                            <label for="PasswordConfirm">New Password (Confirm)</label>
                            <input type="password" class="form-control @{ if (isPasswordsDoNotMatch || isPasswordUpdateError) { WriteLiteral("is-invalid"); } }" id="PasswordConfirm" name="PasswordConfirm" value="">
                            @if (isPasswordsDoNotMatch) 
                            {
                                <div class="invalid-feedback">
                                    The new passwords entered do not match.  Please try again.
                                </div>                                
                            }
                            else if (isPasswordUpdateError)
                            {
                                <div class="invalid-feedback">
                                    The password could not be updated.  Please try again.
                                </div>
                            }
                        </div>
                    </div>
                    <br />
                </div>                
                <div class="form-group">
                    <label for="FirstName">First name</label>
                    <input type="text" class="form-control" id="FirstName" name="FirstName" value="@ViewBag.User.FirstName" required>                    
                    <div class="invalid-feedback">
                        Please enter a first name.
                    </div>
                </div>
                <div class="form-group">
                    <label for="LastName">Last name</label>
                    <input type="text" class="form-control" id="LastName" name="LastName" value="@ViewBag.User.LastName" required>
                    <div class="invalid-feedback">
                        Please enter a last name.
                    </div>
                </div>                
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="email" class="form-control" id="Email" name="Email" value="@ViewBag.User.Email" required>
                    <div class="invalid-feedback">
                        Please enter an email address.
                    </div>
                </div>
                <div class="form-group">
                    <label for="Phone">Phone</label>
                    <input type="tel" class="form-control @{ if (isSMSUpdateError) { WriteLiteral("is-invalid"); } }" id="Phone" name="Phone" value="@ViewBag.User.Phone" required>
                    <div class="invalid-feedback">
                        @if (isSMSUpdateError) 
                        { 
                            <span>The phone number could not be saved as a sign-in factor.  Please try again.</span>
                        }
                        else 
                        {
                            <span>Please enter a phone number.</span>
                        }                        
                    </div>
                </div>
                <div class="form-group">
                    <label for="Claims">Permissions</label>
                    <select multiple class="custom-select" id="Claims" name="Claims" required>
                        @if (isAdmin) 
                        { 
                            <option value="Admin" selected>Admin</option>
                        }
                        else
                        {
                            <option value="Admin">Admin</option>
                        }

                        @if (isRead) 
                        { 
                            <option value="Read" selected>Read</option>
                        }
                        else
                        {
                            <option value="Read">Read</option>
                        }                        
                    </select>
                    <div class="invalid-feedback">
                        Please select at least one permission.
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
}

<br />
<p>
    <a class="btn btn-info btn" asp-area="" asp-controller="Secure" asp-action="Index">&laquo; Go Back</a>
</p>

@section Scripts {
    <script>
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                            scrollToFirstError();
                        }
                        else {
                            showLoader();
                        }

                        form.classList.add('was-validated');                        
                    }, false);
                });
                scrollToFirstError();
            }, false);            
        })();

        function scrollToFirstError() {
            setTimeout(function() {
                if ($('.invalid-feedback:visible').length) {
                    $('html, body').animate({
                        scrollTop: $('.invalid-feedback:visible').first().offset().top - 250
                    }, 500);
                }
            }, 500);            
        }
    </script>

    @{
        var isPasswordsDoNotMatch = Model.Reason == UserProfileUpdateResultReason.PasswordsDoNotMatch;
        var isPasswordUpdateError = Model.Reason == UserProfileUpdateResultReason.PasswordUpdateError;
        if (isPasswordsDoNotMatch || isPasswordUpdateError) 
        {
            <script>
                $(function() {
                    $('#updatePassword').collapse('show');
                });
            </script>
        }
    }
}